from __future__ import annotations

from backend.capabilities.models import CapabilitySpec
from backend.compiler.capability_autobind import auto_bind_required_capabilities
from backend.context.models import ContextGraph, Constraint
from backend.workflow.models import Node, Trigger, WorkflowIR


def _workflow() -> WorkflowIR:
    return WorkflowIR(
        ir_version="0.1",
        id="autobind",
        name="Autobind",
        description="test",
        trigger=Trigger(
            id="start",
            type="trigger",
            name="Start",
            config={"mode": "manual"},
        ),
        nodes=[
            Node(
                id="agent",
                type="agent",
                name="Agent",
                config={"tools": []},
            ),
            Node(
                id="output",
                type="output",
                name="Output",
                config={},
            ),
        ],
        edges=[
            {"from": "start", "to": "agent"},
            {"from": "agent", "to": "output"},
        ],
        variables=[],
        policies=[],
        tests=[],
    )


def test_autobind_adds_read_capability_to_agent():
    capability = CapabilitySpec(
        id="synth:search:abc123",
        kind="synthesized",
        name="Synthesized search adapter",
        description="Read search results",
        access="read",
        side_effecting=False,
        tags=["search", "synthesized"],
    )

    result, changes = auto_bind_required_capabilities(
        _workflow(),
        ContextGraph(capabilities=[capability]),
    )

    agent = next(node for node in result.nodes if node.id == "agent")
    assert capability.id in agent.config["tools"]
    assert changes


def test_autobind_puts_write_capability_behind_approval():
    capability = CapabilitySpec(
        id="synth:email:abc123",
        kind="synthesized",
        name="Synthesized email adapter",
        description="Send email",
        access="write",
        side_effecting=True,
        requires_human_approval=True,
        tags=["email", "synthesized"],
    )

    context = ContextGraph(
        capabilities=[capability],
        constraints=[
            Constraint(
                id="allow-email",
                statement="Email sends are permitted only through explicit approval.",
                severity="blocking",
            )
        ],
    )

    result, changes = auto_bind_required_capabilities(
        _workflow(),
        context,
    )

    kinds = {node.type for node in result.nodes}
    assert "human_approval" in kinds
    assert "tool" in kinds

    tool = next(
        node for node in result.nodes
        if node.type == "tool"
        and node.config.get("tool_ref") == capability.id
    )
    assert tool.policy_ref == "policy-autogenerated-side-effects"
    assert "allow-email" in tool.config["constraint_refs"]

    edge_pairs = {(edge["from"], edge["to"]) for edge in result.edges}
    approval = next(node for node in result.nodes if node.type == "human_approval")
    assert (approval.id, tool.id) in edge_pairs
    assert any(
        "write capability" in change
        for change in changes
    )


def test_autobind_uses_goal_to_ignore_unrelated_context_capabilities():
    email = CapabilitySpec(
        id="synth:email:goal",
        kind="synthesized",
        name="Email adapter",
        description="Send email",
        access="write",
        side_effecting=True,
        requires_human_approval=True,
        tags=["email", "synthesized"],
    )
    slack = CapabilitySpec(
        id="synth:slack:unrelated",
        kind="synthesized",
        name="Slack adapter",
        description="Post messages",
        access="write",
        side_effecting=True,
        requires_human_approval=True,
        tags=["slack", "synthesized"],
    )

    result, _ = auto_bind_required_capabilities(
        _workflow(),
        ContextGraph(capabilities=[email, slack]),
        goal="Every morning send a summary to my email inbox.",
    )

    refs = {
        node.config.get("tool_ref")
        for node in result.nodes
        if node.type == "tool"
    }
    assert email.id in refs
    assert slack.id not in refs
