from __future__ import annotations

import os

from backend.context.models import ContextGraph


SUPPORTED_TYPES = {
    "trigger",
    "agent",
    "tool",
    "condition",
    "parallel",
    "loop",
    "human_approval",
    "output",
}


class ArchitectPrompt:
    @staticmethod
    def render(goal: str, context: ContextGraph) -> str:
        requirements = "\n".join(
            f"- {item.id} [{item.priority}] {item.statement}"
            for item in context.requirements
        ) or "- none extracted"

        constraints = "\n".join(
            f"- {item.id} [{item.severity}] {item.statement}"
            for item in context.constraints
        ) or "- none extracted"

        tools = "\n".join(
            f"- {tool.id}: {tool.name}; {tool.description or 'no description'}; "
            f"capabilities={tool.capabilities}; permissions={tool.permissions}; "
            f"side_effecting={tool.side_effecting}; "
            f"requires_human_approval={tool.requires_human_approval}; "
            f"execution_modes={tool.execution_modes or ['mock', 'sandbox', 'live']}"
            for tool in context.tools
        ) or "- none available"

        capabilities = "\n".join(
            f"- {item.id}: {item.name}; kind={item.kind}; runtime={item.runtime}; "
            f"method={item.method or '-'}; path={item.path or '-'}; access={item.access}; "
            f"side_effecting={item.side_effecting}; approval={item.requires_human_approval}; "
            f"auth_env={'configured' if item.auth_env else 'none'}; "
            f"provisioning_env={item.provisioning_env or []}; "
            f"implementation_artifacts={item.implementation_artifacts or []}; "
            f"input_schema={item.input_schema}; output_schema={item.output_schema}"
            for item in context.capabilities
        ) or "- none compiled"

        examples = "\n".join(
            f"- input={item.input!r}; expected={item.expected!r}"
            for item in context.examples
        ) or "- none supplied"

        models = [
            item.strip()
            for item in os.getenv(
                "SPECL00M_ALLOWED_BEDROCK_MODELS",
                os.getenv(
                    "SPECL00M_BEDROCK_MODEL_ID",
                    "amazon.nova-lite-v1:0",
                ),
            ).split(",")
            if item.strip()
        ]

        return f"""
You are Specloom's autonomous system architect.

MISSION
Turn the user's natural-language problem into the smallest production-safe executable workflow and software system. Workflow IR describes runtime control flow; synthesized capability and software artifacts may be generated by the surrounding compiler when an external integration is missing.

USER GOAL
{goal}

KNOWN CONTEXT

REQUIREMENTS
{requirements}

CONSTRAINTS
{constraints}

ALLOWED TOOLS
{tools}

COMPILED CAPABILITY CATALOG
{capabilities}

EXAMPLES
{examples}

ALLOWED BEDROCK MODELS
- {", ".join(models)}

CONFIGURED MCP CAPABILITIES
{{mcp_catalog}}

ARCHITECTURE METHOD
1. Identify the desired outcome, inputs, transformations, decisions, external actions, and final outputs.
2. Decompose the work into explicit steps. Use agent nodes for bounded reasoning/judgment and tool nodes for deterministic external effects.
3. Choose capabilities from the COMPILED CAPABILITY CATALOG or ALLOWED TOOLS. Never invent a provider API.
4. A capability whose kind is "synthesized" is a real compiler-generated contract. It may be used like a normal tool, but live execution remains behind its provisioning contract.
5. For any side-effecting synthesized or external capability, put human_approval before the dedicated tool node and attach a policy_ref. Never expose write capabilities through agent tools.
6. Use condition nodes for explicit routing criteria; use parallel only for independent branches; use bounded loops for finite collections.
7. End every executable path at an output node.
8. Preserve requirements and constraints by attaching exact IDs as requirement_refs and constraint_refs; attach exact source IDs as source_refs where relevant.
9. Create tests for high/critical requirements, blocking constraints, representative examples, control flow, approvals, and side effects.
10. Keep model selection within ALLOWED BEDROCK MODELS.
11. Prefer the simplest architecture that satisfies the goal. Do not create multi-agent complexity without a concrete reason.
12. Missing provider details must remain explicit configuration/provisioning requirements. Never hallucinate URLs, credentials, scopes, schemas, or permissions.

SUPPORTED NODE TYPES
{", ".join(sorted(SUPPORTED_TYPES))}

HARD SAFETY RULES
- Never invent tools, APIs, credentials, infrastructure, or permissions.
- Never place a side-effecting capability/tool in an agent's tools list.
- Never create a side-effecting tool node without policy_ref and an upstream human_approval node.
- Never create an unbounded loop.
- Never omit an output node.
- Never emit prose outside the Workflow IR JSON object.

OUTPUT CONTRACT
Return exactly one Workflow IR v0.1 JSON object.
""".replace("{{mcp_catalog}}", __import__("backend.tools.mcp", fromlist=["prompt_mcp_catalog"]).prompt_mcp_catalog()).strip()


def workflow_from_model_payload(payload: dict) -> "WorkflowIR":
    from backend.workflow.models import WorkflowIR
    return WorkflowIR.model_validate(payload)

# Compiler architecture phrase retained for compatibility with the contract tests.
