from __future__ import annotations

import re

from backend.capabilities.models import CapabilitySpec
from backend.context.models import ContextGraph
from backend.workflow.models import Node, WorkflowIR

from .broker import CapabilityBroker
from .decomposition import ProblemDecomposition
from .models import CapabilityRequirement
from .synthesizer import infer_capability_requirements


_AUTOGEN_POLICY_ID = "policy-autogenerated-side-effects"


def auto_bind_required_capabilities(
    workflow: WorkflowIR,
    context: ContextGraph,
    requirements: list[CapabilityRequirement] | None = None,
    *,
    goal: str | None = None,
    problem_decomposition: ProblemDecomposition | None = None,
) -> tuple[WorkflowIR, list[str]]:
    """Make required capability use explicit in Workflow IR before validation."""
    capability_requirements = requirements or (
        infer_capability_requirements(
            goal,
            context,
            problem_decomposition=problem_decomposition,
        )
        if goal
        else [
            # Direct callers without a goal retain the legacy conservative behavior.
            CapabilityRequirement(
                id=f"capreq:{capability.id}",
                family=_family(capability),
                purpose=capability.description or capability.name,
                access=capability.access,
                external=capability.kind in {"synthesized", "openapi", "configured_api", "mcp"},
                required=True,
            )
            for capability in context.capabilities
        ]
    )

    plans = CapabilityBroker().plan(
        capability_requirements,
        context,
    )

    nodes = [node.model_copy(deep=True) for node in workflow.nodes]
    edges = [dict(edge) for edge in workflow.edges]
    policies = [dict(policy) for policy in workflow.policies]
    changes: list[str] = []

    node_map = {workflow.trigger.id: workflow.trigger, **{node.id: node for node in nodes}}
    agent_nodes = [node for node in nodes if node.type == "agent"]

    for plan in plans:
        selected = plan.selected
        if selected is None or not plan.requirement_id:
            continue
        capability = next(
            (
                item
                for item in context.capabilities
                if item.id == selected.capability_id
            ),
            None,
        )
        if capability is None:
            continue

        if capability.side_effecting:
            nodes, edges, policies, changed = _bind_write_capability(
                nodes,
                edges,
                policies,
                workflow,
                capability,
                set(item.id for item in context.constraints if item.severity == "blocking"),
            )
            changes.extend(changed)
        else:
            if not agent_nodes:
                continue
            target = agent_nodes[0]
            updated_tools = [str(value) for value in target.config.get("tools", [])]
            if capability.id not in updated_tools:
                updated_tools.append(capability.id)
                target.config["tools"] = updated_tools
                if requirements and plan.requirement_id in {item.id for item in requirements}:
                    refs = target.config.setdefault("requirement_refs", [])
                    if plan.requirement_id not in refs:
                        refs.append(plan.requirement_id)
                changes.append(
                    f"bound read capability {capability.id} to agent {target.id}"
                )

    return workflow.model_copy(
        update={
            "nodes": nodes,
            "edges": edges,
            "policies": policies,
        }
    ), changes





def _bind_write_capability(
    nodes: list[Node],
    edges: list[dict],
    policies: list[dict],
    workflow: WorkflowIR,
    capability: CapabilitySpec,
    blocking_constraint_ids: set[str],
) -> tuple[list[Node], list[dict], list[dict], list[str]]:
    for node in nodes:
        if (
            node.type == "tool"
            and str(node.config.get("tool_ref")) == capability.id
        ):
            return nodes, edges, policies, []

    approval_id = _unique_node_id("approve_" + _slug(capability.id), nodes, workflow.trigger.id)
    tool_id = _unique_node_id("tool_" + _slug(capability.id), nodes, workflow.trigger.id)
    output_candidates = [node for node in nodes if node.type == "output"]
    if not output_candidates:
        return nodes, edges, policies, []
    output = output_candidates[0]

    incoming = [
        edge for edge in edges
        if edge.get("to") == output.id
    ]
    if len(incoming) != 1:
        return nodes, edges, policies, [
            f"could not auto-bind write capability {capability.id}: output path is ambiguous"
        ]

    predecessor = str(incoming[0].get("from"))
    edges = [edge for edge in edges if not (
        edge.get("from") == predecessor and edge.get("to") == output.id
    )]
    edges.extend(
        [
            {"from": predecessor, "to": approval_id},
            {"from": approval_id, "to": tool_id},
            {"from": tool_id, "to": output.id},
        ]
    )

    if not any(str(policy.get("id")) == _AUTOGEN_POLICY_ID for policy in policies):
        policies.append(
            {
                "id": _AUTOGEN_POLICY_ID,
                "name": "Autogenerated Side Effect Policy",
                "description": "Compiler-generated write capability gate; live side effects require explicit approval.",
            }
        )

    tool = Node(
        id=tool_id,
        type="tool",
        name=f"Execute {capability.name}",
        description="Compiler-generated dedicated capability invocation.",
        config={
            "tool_ref": capability.id,
            "mode": "mock",
            "requirement_refs": [],
            "constraint_refs": sorted(blocking_constraint_ids),
        },
        policy_ref=_AUTOGEN_POLICY_ID,
    )
    approval = Node(
        id=approval_id,
        type="human_approval",
        name=f"Approve {capability.name}",
        description="Compiler-generated approval gate for a side-effecting capability.",
        config={"reason": f"Approve use of {capability.id}"},
        policy_ref=_AUTOGEN_POLICY_ID,
    )
    nodes.extend([approval, tool])

    return nodes, edges, policies, [
        f"bound write capability {capability.id} through {approval_id} -> {tool_id}"
    ]


def _family(capability: CapabilitySpec) -> str:
    for tag in capability.tags:
        if tag not in {"api", "openapi", "synthesized", "generated_http"}:
            return str(tag)
    if capability.id.startswith("synth:"):
        parts = capability.id.split(":")
        if len(parts) > 1:
            return parts[1]
    return capability.name.split()[0].lower()


def _slug(value: str) -> str:
    import re
    clean = re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_").lower()
    return clean or "capability"


def _unique_node_id(base: str, nodes: list[Node], trigger_id: str) -> str:
    used = {trigger_id, *(node.id for node in nodes)}
    candidate = base
    index = 2
    while candidate in used:
        candidate = f"{base}_{index}"
        index += 1
    return candidate
