from __future__ import annotations

import hashlib
import re
from typing import Iterable

from backend.capabilities.models import CapabilitySpec
from backend.context.models import ContextGraph

from .models import CapabilityRequirement, SynthesizedCapabilityPlan


_FAMILY_PATTERNS: dict[str, tuple[str, ...]] = {
    "email": (r"\b(email|e-mail|mailbox|inbox|smtp)\b",),
    "slack": (r"\bslack\b",),
    "calendar": (r"\b(calendar|meeting|appointment)\b",),
    "database": (r"\b(database|postgres(?:ql)?|mysql|sqlite|sql)\b",),
    "jira": (r"\bjira\b",),
    "linear": (r"\blinear\b",),
    "sms": (r"\b(sms|text message|twilio)\b",),
    "storage": (r"\b(s3|object storage|bucket|file storage|upload file)\b",),
    "payments": (r"\b(payment|stripe|checkout|charge|refund)\b",),
    "notification": (r"\b(notification|notify|alert|escalat)\b",),
    "browser": (r"\b(browser|website|web page|navigate|click|scrape)\b",),
}

_ACTION = re.compile(
    r"\b(send|create|update|delete|publish|upload|post|book|notify|message|charge|refund|sync|write)\b",
    re.I,
)


def synthesize_missing_capabilities(
    goal: str,
    context: ContextGraph,
) -> tuple[list[CapabilitySpec], list[CapabilityRequirement], list[SynthesizedCapabilityPlan]]:
    """Create explicit provider-neutral capability contracts for missing integrations.

    The synthesizer never invents provider endpoints. External details remain configuration
    inputs or are filled later from an official API/OpenAPI source. This turns a missing
    integration from a compiler dead-end into an implementation artifact with a hard
    provisioning boundary.
    """
    available = _available_tokens(context)
    capabilities: list[CapabilitySpec] = []
    requirements: list[CapabilityRequirement] = []
    plans: list[SynthesizedCapabilityPlan] = []

    for family, patterns in _FAMILY_PATTERNS.items():
        if not any(re.search(pattern, goal, re.I) for pattern in patterns):
            continue
        if _family_available(family, available):
            continue

        access = "write" if _ACTION.search(goal) else "read"
        capability_id = _stable_capability_id(family, goal)
        env_prefix = "SPECL00M_SYNTH_" + re.sub(r"[^A-Za-z0-9]+", "_", family).upper()
        plan = SynthesizedCapabilityPlan(
            capability_id=capability_id,
            family=family,
            rationale=(
                f"No trusted {family} integration is configured; synthesize a provider-neutral "
                "adapter contract instead of hallucinating an API."
            ),
            runtime="generated_http",
            provisioning_env=[
                f"{env_prefix}_BASE_URL",
                f"{env_prefix}_PATH",
                f"{env_prefix}_METHOD",
                f"{env_prefix}_API_KEY",
            ],
            artifact_paths=[
                f"generated/capabilities/{family}.py",
                f"generated/tests/test_{family}.py",
            ],
            configuration_required=True,
        )
        requirements.append(
            CapabilityRequirement(
                id=f"capreq_{family}",
                family=family,
                purpose=f"Provide the {family} capability requested by the user's goal.",
                access=access,
                external=True,
                required=True,
            )
        )
        capabilities.append(
            CapabilitySpec(
                id=capability_id,
                kind="synthesized",
                name=f"Synthesized {family} adapter",
                description=(
                    f"Provider-neutral {family} capability generated by Specloom; "
                    "endpoint/auth configuration is supplied separately."
                ),
                access=access,
                permissions=["READ", "WRITE"] if access == "write" else ["READ"],
                side_effecting=access == "write",
                requires_human_approval=access == "write",
                tags=[family, "synthesized", "generated_http"],
                input_schema={
                    "type": "object",
                    "additionalProperties": True,
                    "description": f"Payload for the configured {family} adapter.",
                },
                output_schema={"type": "object", "additionalProperties": True},
                runtime="generated_http",
                implementation_artifacts=plan.artifact_paths,
                provisioning_env=plan.provisioning_env,
                synthesis_reason=plan.rationale,
                execution_modes=["mock", "sandbox", "live"],
            )
        )
        plans.append(plan)

    return capabilities, requirements, plans


def _available_tokens(context: ContextGraph) -> set[str]:
    tokens: set[str] = set()
    for tool in context.tools:
        tokens.update(str(value).lower() for value in tool.capabilities)
        tokens.add(tool.name.lower())
        tokens.add(tool.id.lower())
    for capability in context.capabilities:
        tokens.update(str(value).lower() for value in capability.tags)
        tokens.add(capability.name.lower())
        tokens.add(capability.id.lower())
    return tokens


def _family_available(family: str, available: Iterable[str]) -> bool:
    candidates = {family, family.rstrip("s"), family.replace("notification", "notify")}
    return any(
        candidate in token or token in candidate
        for token in available
        for candidate in candidates
    )


def _stable_capability_id(family: str, goal: str) -> str:
    digest = hashlib.sha1(f"{family}:{goal.strip().lower()}".encode("utf-8")).hexdigest()[:10]
    return f"synth:{family}:{digest}"
